# -*- coding: utf-8 -*-
"""Fake_Social_media_Account_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bM1i1MFu50WsOSU509uIiX4RYc6-L810
"""

import sys
import numpy as np
print(sys.version)

#!pip install pandas numpy scikit-learn

import pandas as pd
df = pd.read_csv("final-v1.csv")

df.head()

df.shape

df.info()

print(df.duplicated().sum())

df = df.drop_duplicates()

df.shape

df["is_fake"].unique()

df["is_fake"].value_counts(normalize=True)

import matplotlib.pyplot as plt

df["is_fake"].value_counts().plot(kind="bar")
plt.title("Fake vs Real Accounts")
plt.xlabel("0 = Real, 1 = Fake")
plt.ylabel("Count")
plt.show()

# Features (all columns except target)
X = df.drop("is_fake", axis=1)

# Target
Y = df["is_fake"]

X.head()
Y.head()

print("X shape:", X.shape)
print("Y shape:", Y.shape)

import matplotlib.pyplot as plt

plt.hist(df["edge_followed_by"], bins=30)
plt.title("Followers Distribution")
plt.xlabel("Number of Followers")
plt.ylabel("Frequency")
plt.show()

# Numeric columns (need scaling)
numeric_cols = [
    "edge_followed_by",
    "edge_follow",
    "username_length",
    "full_name_length"
]

# Binary columns (NO scaling needed)
binary_cols = [
    "username_has_number",
    "full_name_has_number",
    "is_private",
    "is_joined_recently",
    "has_channel",
    "is_business_account",
    "has_guides",
    "has_external_url"
]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Scale numeric columns
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

import joblib

joblib.dump(scaler, "scaler.pkl")

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

print("Training set:", X_train.shape, y_train.shape)
print("Testing set:", X_test.shape, y_test.shape)

print("Train label distribution:")
print(y_train.value_counts(normalize=True))

print("\nTest label distribution:")
print(y_test.value_counts(normalize=True))

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(X_train, y_train)

# Predict labels for test data
y_pred = rf_model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Get importance scores
importances = rf_model.feature_importances_

feature_importance_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

feature_importance_df

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.barh(feature_importance_df["Feature"], feature_importance_df["Importance"])
plt.gca().invert_yaxis()
plt.title("Feature Importance in Fake Account Detection")
plt.xlabel("Importance Score")
plt.ylabel("Feature")
plt.show()

feature_importance_df.head(5)

import joblib

joblib.dump(rf_model, "fake_account_rf_model.pkl")

!ls

loaded_model = joblib.load("fake_account_rf_model.pkl")

# Test a prediction (no output needed to understand value)
loaded_model.predict(X_test[:5])

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# 
# # Load model and scaler
# model = joblib.load("fake_account_rf_model.pkl")
# scaler = joblib.load("scaler.pkl")
# 
# st.title("Fake Social Media Account Detection")
# st.write("Model and scaler loaded successfully!")
#

!streamlit run app.py

